### PR TITLE
chore: bump sandbox version default for SDK change

### PR DESCRIPTION
**Pull request by austinabell**
commit is `1.26.0-rc.2` for now -- tested it works against https://github.com/near/near-sdk-rs/pull/742

### CODE REVIEW

**Review by ChaoticTempest — APPROVED** [review]

**Review by itegulov — COMMENTED** [review]
While this works for Linux-x86_64, the same binary is not available for Darwin-x86_64: https://s3-us-west-1.amazonaws.com/build.nearprotocol.com/nearcore/Darwin-x86_64/1.26.0/57b6ac92b0e77deade8a6eef1a322272511aa5de/near-sandbox.tar.gz

This is the issue I was talking about the other day

**Comment by ChaoticTempest** [comment]
hmmm, I wonder if the `mac-binary.yml` regex pattern isn't catching `-rc.2` naming:
```
    tags:
      - '[0-9]+.[0-9]+.[0-9]+.*'
```

it's really hard to test GitHub Actions. A test for a test

**Comment by austinabell** [comment]
> hmmm, I wonder if the `mac-binary.yml` regex pattern isn't catching `-rc.2` naming:
> 
> ```
>     tags:
>       - '[0-9]+.[0-9]+.[0-9]+.*'
> ```
> 
> it's really hard to test GitHub Actions. A test for a test

Nah the regex matches, not sure here. Maybe has to do with the fact that the tagged commit isn't on master?

**Comment by ChaoticTempest** [comment]
> I think it might be because the regex is in ''

yeah that could be it and if so, we should probably get in a fix before 1.26 complete rolls out

**Comment by austinabell** [comment]
> > I think it might be because the regex is in ''
> 
> yeah that could be it and if so, we should probably get in a fix before 1.26 complete rolls out

Not sure though, actions docs are inconsistent, but can see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-branches-and-tags shows no `'`. Or the issue is just that the tag is applied after push and then the workflow is not run -- more likely?

**Comment by ChaoticTempest** [comment]
yeah let's just roll this one in. We were previously using a non-stable commit too. We can fix the regex in the meantime

**Pull request merged**
